name       : enca
version    : 1.18
release    : 1
source     :
    - https://github.com/nijel/enca/archive/1.18.tar.gz : b87c8d1bffc7d06ba74f82ae86eb21a921e94629203b2a971c966064c7eadab2
license    : GPL-2.0
summary    : Extremely Naive Charset Analyser
component  : programming.library
description: |
    Enca - guess and convert encoding of text files
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
